### ISSUE TITLE
Controller.getName() should work with disconnected controllers

### ISSUE THREAD

**Issue by klianc09** [MrStahlfelge/gdx-controllerutils#20]
Using the default libgdx controller implementation, I used to show the name of the controller that disconnected in the `ControllerListener`. However when using the jamepad implementation on desktop, it makes a native call to the SDL layer whenever retrieving the name, which of course will no longer work in the "disconnected" event handler when the controller is already disconnected. Which causes a `disconnected()` event to be fired, which triggers my listener again which results in a Stackoverflow eventually.

I know I can workaround that by querying the name of the controller upon connect() and store it in a map, to later retrieve it for the disconnect message. But I feel like that's something the library should do for me. As far as I understand, the name of a controller can't change anyway, so the `JamepadController` should just query its name in the beginning and then just return a local field anytime somebody calls `getName()`. As I see it, there is no need to call into the SDL layer each time `getName()` is called.

**Comment by MrStahlfelge** [comment]
You are right that it will work this way for Jamepad, but not on GWT, Android or iOS. So it is up to you to store the map of device names that were connected.

The behaviour that the disconnected event is fired on an already disconnected controller was fixed with the last commit on Feb 13, it's just not in a release yet. But thanks for reporting this!

**Comment by MrStahlfelge** [comment]
Released 1.0.1 with the fix for the disconnected event loop.
