### ISSUE TITLE
0.2.0 disconnect/connect events not triggering on desktop

### ISSUE THREAD

**Issue by tomcashman** [MrStahlfelge/gdx-controllerutils#9]
I've been using 0.2.0 and found that connect/disconnect events aren't working on desktop. I'm using Windows 10 64 bit + Java 8.

**Comment by MrStahlfelge** [comment]
Hi, is it working for you with v0.1.2?

**Comment by MrStahlfelge** [comment]
And another question: Is the problem that just the events are not triggered, or is it that hotplugging does not work at all? Is the `Controllers.getControllers()` changing for you?

**Comment by tomcashman** [comment]
I can test 0.1.2 this evening. My current sequence of events are as follows:

- Add a listener to the Controller
- Unplug the Controller (disconnect method not called)
- Plug in the Controller (connect method not called)

**Comment by MrStahlfelge** [comment]
I can confirm. I didn't notice this because I don't use listeners per controller, but just a listener on the ControllerManager (`Controllers.addListener()`. The pushed commit changes it.

However, a reconnect can not be fired. Jamepad does not reuse the same index and object in general on reconnects, indeed often the controller index array is completely rearranged just on a disconnect. Unfortunately, this is a behaviour that is the same on GWT, too. I can just recommend you to completely design the games in a way that players that were disconnected have to reconnect their controller in game. If you see a way to improve the situation, I am happy to accept PRs.
